apiVersion: v1
kind: Service
metadata:
  name: cicddemo
  labels:
    name: cicddemo
spec:
  selector:
    run: cicddemo
  type: LoadBalancer
  loadBalancerIP: service_ip
  sessionAffinity: ClientIP
  ports:
    - protocol: "TCP"
      port: 7002
      targetPort: 7002
      name: cicddemo-http

